# Generated by Django 4.1.3 on 2022-11-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='unread_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=256)),
                ('payload', models.CharField(max_length=2048)),
                ('receiver', models.CharField(max_length=256)),
            ],
        ),
    ]
